name: Build Arcana Beta APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Dependências e Build Next.js
        run: |
          npm install
          npm run build

      - name: Sincronizar Versão e Configurar Assets
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          
          # Pega a versão do package.json e coloca numa variável
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "Sincronizando com a versão: $APP_VERSION"
          
      - name: Sincronizar Versão
         run: |
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version
          npx cap sync android
         
          # Gerando Ícones e Splash
          npm install @capacitor/assets
          mkdir -p assets
          cp public/images/icon.png assets/icon.png
          cp public/images/logo-do-app.png assets/splash.png
          npx capacitor-assets generate --android
          
          npx cap sync android

      - name: Compilar APK (Debug)
        run: |
          cd android && ./gradlew assembleDebug

      - name: Upload APK Final
        uses: actions/upload-artifact@v4
        with:
          name: StylesAi-Beta-Build
          path: android/app/build/outputs/apk/debug/app-debug.apk
