name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Instalar Dependências
        run: npm install

      - name: Extrair Versão do package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "versao=$VERSION" >> $GITHUB_OUTPUT
          echo "Sincronizando com a versão: $VERSION"

      - name: Build Next.js
        run: npm run build

      - name: Sincronizar com Capacitor e Atualizar Versão Android
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android
          
          # ATUALIZA A VERSÃO NO ANDROID
          VERSION="${{ steps.get_version.outputs.versao }}"
          # Muda o versionName para o que está no package.json
          sed -i "s/versionName \".*\"/versionName \"$VERSION\"/" android/app/build.gradle
          # Muda o versionCode para o número do build do GitHub (número inteiro sempre crescente)
          sed -i "s/versionCode [0-9]*/versionCode ${{ github.run_number }}/" android/app/build.gradle

      - name: Gerar Ícones e Splash
        run: |
          npm install @capacitor/assets
          mkdir -p assets
          cp public/images/icon.png assets/icon.png || true
          cp public/images/logo-do-app.png assets/splash.png || true
          npx capacitor-assets generate --android
          npx cap sync android

      - name: Compilar APK (Release)
        run: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Otimizar e Assinar APK
        id: sign_app
        run: |
          BUILD_TOOLS_PATH=$(ls -d ${ANDROID_SDK_ROOT}/build-tools/* | tail -1)
          
          UNSIGNED_APK="android/app/build/outputs/apk/release/app-release-unsigned.apk"
          ALIGNED_APK="Arcana-aligned.apk"
          SIGNED_APK="Arcana-v${{ steps.get_version.outputs.versao }}.apk"
          
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
          
          $BUILD_TOOLS_PATH/zipalign -v 4 "$UNSIGNED_APK" "$ALIGNED_APK"
          
          $BUILD_TOOLS_PATH/apksigner sign --ks release.keystore \
            --ks-key-alias "${{ secrets.ANDROID_KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.ANDROID_KEY_PASSWORD }}" \
            --out "$SIGNED_APK" \
            "$ALIGNED_APK"
          
          echo "signed_file=$SIGNED_APK" >> $GITHUB_OUTPUT
          rm release.keystore

      - name: Upload APK Assinado
        uses: actions/upload-artifact@v4
        with:
          name: Arcana-v${{ steps.get_version.outputs.versao }}
          path: ${{ steps.sign_app.outputs.signed_file }}
